backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "public/data/products.json"
        label: "Product List"
        name: "productlist"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Phone"
            name: "phone"
            widget: "string"
            required: false
          - label: "Image"
            name: "image"
            widget: "image"
            required: false
          - label: "Order"
            name: "order"
            widget: "number"
            required: false 